version: "2.0"
services:
  db:
    environment: 
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
    image: mariadb
    ports:
      - "8889:3306"
    restart: always
    volumes: 
      - "./mysql:/var/lib/mysql"
  web:
    environment: 
      - ALLOW_OVERRIDE=true
    image:  tutum/apache-php
    links:
      - db
    ports:
      - "8008:80"
    volumes: 
      - "./app:/app"